apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: bb-app
  type: NodePort
  ports:
    - name: quic
      protocol: UDP
      port: 4433
      targetPort: 4433
      nodePort: 30403
